# Generated by Django 5.2 on 2025-06-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100)),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField()),
                ('service', models.CharField(choices=[('DTA1', 'DTA - Day Program (Adult) - 1'), ('DTA2', 'DTA - Day Program (Adult) - 2'), ('DTT', 'DTT - Day Treatment Training'), ('SDTA', 'Special DTA - Special Day Program')], max_length=50)),
                ('location', models.CharField(choices=[('GUADALUPE_DTA', 'GUADALUPE DTA'), ('GUADALUPE_DTT', 'GUADALUPE DTT'), ('GUADALUPE_SPECIAL', 'GUADALUPE SPECIAL DTA')], max_length=50)),
                ('date', models.DateField()),
                ('one_on_one', models.BooleanField(default=False)),
                ('documentation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'client'],
                'unique_together': {('client', 'date')},
            },
        ),
    ]
