# Generated by Django 5.2 on 2025-06-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
