# Generated by Django 5.2 on 2025-06-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_usersettings_address2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='address2',
            field=models.CharField(blank=True, default='1', max_length=255),
            preserve_default=False,
        ),
    ]
