# Generated by Django 5.2 on 2025-06-12 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_usersettings_address2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='other', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='location',
            field=models.CharField(choices=[('guadalupe_dta', 'Guadalupe DTA'), ('guadalupe_dtt', 'Guadalupe DTT'), ('guadalupe_special_dta', 'Guadalupe Special DTA'), ('hcbs', 'HCBS')], default='guadalupe_dta', max_length=50),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], default='single', max_length=10),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='payroll_id',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='provider_id',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='race',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='services_provided',
            field=models.TextField(default='None', help_text='List of services provided, separated by commas'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('effective_start', models.DateField()),
                ('effective_end', models.DateField()),
                ('user_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='settings.usersettings')),
            ],
        ),
    ]
