# Generated by Django 5.2 on 2025-06-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_usersettings_additional_info_usersettings_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='race',
            field=models.CharField(choices=[('american_indian', 'American Indian or Alaska Native'), ('asian', 'Asian'), ('black', 'Black or African American'), ('native_hawaiian', 'Native Hawaiian or Other Pacific Islander'), ('white', 'White'), ('two_or_more', 'Two or More Races'), ('not_disclosed', 'Prefer Not to Disclose')], default='not_disclosed', max_length=50),
        ),
    ]
